import { mkdirSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname } from "node:path";
import {
  BitgetRestClient,
  buildTools,
  loadConfig,
  safeInvoke,
  type ToolContext,
  type ToolSpec,
} from "@bitget-ai/bitget-agent-sdk";

/**
 * The verbs Vidiyal reads a real account through, plus the write verb it only ever
 * previews. account_overview and raw account bills take no action, so they are asked
 * for as a whole tool. Bitget files bills under funds_records, not under
 * account_overview, so the equity curve reads financial records.
 */
const TARGETS: Array<{ tool: string; action?: string }> = [
  { tool: "order" },
  { tool: "order", action: "fills" },
  { tool: "order", action: "history" },
  { tool: "order", action: "detail" },
  { tool: "order", action: "place" },
  { tool: "position" },
  { tool: "position", action: "info" },
  { tool: "position", action: "history" },
  { tool: "account_overview" },
  { tool: "funds_records", action: "financial" },
  { tool: "tax", action: "records" },
];

const OUT = "docs/dev/account-schemas.md";

async function dump(
  discover: ToolSpec,
  ctx: ToolContext,
  args: Record<string, unknown>,
): Promise<string> {
  const res = await safeInvoke(discover, args, ctx);
  if (!res.ok) {
    return JSON.stringify(res, null, 2);
  }
  return JSON.stringify(res.data, null, 2);
}

async function main(): Promise<void> {
  const config = loadConfig({ modules: "all", readOnly: true });
  const client = new BitgetRestClient(config);
  const ctx: ToolContext = { config, client };
  const discover = buildTools(config).find((t) => t.name === "discover");
  if (!discover) {
    throw new Error("the SDK did not build a discover tool");
  }

  const parts: string[] = [
    "# Bitget account tool schemas, copied from the SDK",
    "",
    "Generated by `npm run discover` against @bitget-ai/bitget-agent-sdk. Every parameter",
    "name in src/ingest/account.ts and src/checklist/gate.ts comes from this file, not from",
    "a guess. Discovery needs no API key. Regenerate after an SDK upgrade and read the diff",
    "before changing any caller.",
    "",
    `SDK version: ${readSdkVersion()}`,
    `Generated: ${new Date().toISOString()}`,
    "",
  ];

  for (const target of TARGETS) {
    const heading = target.action ? `${target.tool} action: ${target.action}` : `tool: ${target.tool}`;
    parts.push(`## ${heading}`, "", "```json", await dump(discover, ctx, { ...target }), "```", "");
  }

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, parts.join("\n"), { encoding: "utf8" });
  console.log(`wrote ${OUT} with ${TARGETS.length} schemas`);
}

function readSdkVersion(): string {
  const pkg = createRequire(import.meta.url)("@bitget-ai/bitget-agent-sdk/package.json") as {
    version: string;
  };
  return pkg.version;
}

await main();
